/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 23-may.-2023 21:17:55 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "CLIENTE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "CUENTA" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "MOVIMIENTO" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE  "CLIENTE"
(
	"K_TIPO_ID" VARCHAR(3) NOT NULL,    -- Tipo de id del cliente involucrado
	"K_NUMERO_ID" NUMBER(15) NOT NULL,    -- Numero de id del cliente involucrado
	"N_NOMBRECOMPLETO" VARCHAR(100) NOT NULL    -- Nombre completo del cliente
)
;

CREATE TABLE  "CUENTA"
(
	"K_NUMERO_CUENTA" NUMBER(15) NOT NULL,    -- Numero de cuenta del cliente
	"I_TIPO_ID" VARCHAR(3) NOT NULL,    -- Tipo id del cliente
	"Q_NUMERO_ID" NUMBER(15) NOT NULL,    -- Numero id del cliente
	"Q_SALDO" NUMBER(20,2) NOT NULL    -- Saldo de la cuenta del cliente actual
)
;

CREATE TABLE  "MOVIMIENTO"
(
	"K_ID_MOVIMIENTO" NUMBER(10) NOT NULL,    -- Id del movimiento bancario
	"Q_NUMERO_CUENTA" NUMBER(20) NOT NULL,    -- Numero de cuenta
	"I_TIPO_CUENTA" VARCHAR(15) NOT NULL,    -- Tipo de cuenta bancaria
	"Q_MOVIMIENTO" NUMBER(20,2) NOT NULL    -- Movimiento realizado desde la cuenta
)
;

/* Create Comments, Sequences and Triggers for Autonumber Columns */

COMMENT ON TABLE  "CLIENTE" IS 'Tabla cliente del banco'
;

COMMENT ON COLUMN  "CLIENTE"."K_TIPO_ID" IS 'Tipo de id del cliente involucrado'
;

COMMENT ON COLUMN  "CLIENTE"."K_NUMERO_ID" IS 'Numero de id del cliente involucrado'
;

COMMENT ON COLUMN  "CLIENTE"."N_NOMBRECOMPLETO" IS 'Nombre completo del cliente'
;

COMMENT ON TABLE  "CUENTA" IS 'Tabla con las cuentas del o los clientes'
;

COMMENT ON COLUMN  "CUENTA"."K_NUMERO_CUENTA" IS 'Numero de cuenta del cliente'
;

COMMENT ON COLUMN  "CUENTA"."I_TIPO_ID" IS 'Tipo id del cliente'
;

COMMENT ON COLUMN  "CUENTA"."Q_NUMERO_ID" IS 'Numero id del cliente'
;

COMMENT ON COLUMN  "CUENTA"."Q_SALDO" IS 'Saldo de la cuenta del cliente actual'
;

COMMENT ON TABLE  "MOVIMIENTO" IS 'Tabla de movimientos bancarios en una cuenta'
;

COMMENT ON COLUMN  "MOVIMIENTO"."K_ID_MOVIMIENTO" IS 'Id del movimiento bancario'
;

COMMENT ON COLUMN  "MOVIMIENTO"."Q_NUMERO_CUENTA" IS 'Numero de cuenta'
;

COMMENT ON COLUMN  "MOVIMIENTO"."I_TIPO_CUENTA" IS 'Tipo de cuenta bancaria'
;

COMMENT ON COLUMN  "MOVIMIENTO"."Q_MOVIMIENTO" IS 'Movimiento realizado desde la cuenta'
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "CLIENTE" 
 ADD CONSTRAINT "PK_CLIENTEBANCO"
	PRIMARY KEY ("K_TIPO_ID","K_NUMERO_ID") 
 USING INDEX
;

ALTER TABLE  "CLIENTE" 
 ADD CONSTRAINT "CK_TIPO_ID_CLIENTE_BANCO" CHECK (K_TIPO_ID IN ('TI', 'CC', 'NIT', 'CE', 'PAP'))
;

ALTER TABLE  "CLIENTE" 
 ADD CONSTRAINT "CK_NUMERO_ID_CLIENTE_BANCO" CHECK (K_NUMERO_ID > 0)
;

ALTER TABLE  "CUENTA" 
 ADD CONSTRAINT "PK_CUENTA"
	PRIMARY KEY ("K_NUMERO_CUENTA") 
 USING INDEX
;

CREATE INDEX "IXFK_CUENTA_CLIENTE"   
 ON  "CUENTA" ("I_TIPO_ID","Q_NUMERO_ID") 
;

ALTER TABLE  "MOVIMIENTO" 
 ADD CONSTRAINT "PK_MOVIMIENTO"
	PRIMARY KEY ("K_ID_MOVIMIENTO","Q_NUMERO_CUENTA") 
 USING INDEX
;

ALTER TABLE  "MOVIMIENTO" 
 ADD CONSTRAINT "CK_" CHECK (I_TIPO_CUENTA IN ('DEBITO', 'CREDITO'))
;

CREATE INDEX "IXFK_MOVIMIENTO_CUENTA"   
 ON  "MOVIMIENTO" ("Q_NUMERO_CUENTA") 
;

/* Create Foreign Key Constraints */

ALTER TABLE  "CUENTA" 
 ADD CONSTRAINT "FK_CUENTA_CLIENTE"
	FOREIGN KEY ("I_TIPO_ID","Q_NUMERO_ID") REFERENCES  "CLIENTE" ("K_TIPO_ID","K_NUMERO_ID")
;

ALTER TABLE  "MOVIMIENTO" 
 ADD CONSTRAINT "FK_MOVIMIENTO_CUENTA"
	FOREIGN KEY ("Q_NUMERO_CUENTA") REFERENCES  "CUENTA" ("K_NUMERO_CUENTA")
;
