
	conn system/admin@localhost:1521/dbmultinivel;

	CREATE TABLESPACE SGADEF DATAFILE 'C:\app\Laura\product\18.0.0\oradata\XE\DBMULTINIVEL\SGADEF.DBF' SIZE 2M AUTOEXTEND ON;
	CREATE TEMPORARY TABLESPACE SGATMP TEMPFILE 'C:\app\Laura\product\18.0.0\oradata\XE\DBMULTINIVEL\SGATMP.DBF' SIZE 2M AUTOEXTEND ON;
	


	CREATE USER U_ADMIN IDENTIFIED BY pass
	DEFAULT TABLESPACE SGADEF
	TEMPORARY TABLESPACE SGATMP
	QUOTA 2M ON SGADEF;

	CREATE ROLE R_ADMIN;
	

	GRANT CREATE ROLE TO R_ADMIN;
	GRANT CONNECT TO R_ADMIN;
	GRANT CREATE USER TO R_ADMIN;
	GRANT GRANT ANY PRIVILEGE TO R_ADMIN;
	GRANT CREATE TABLE TO R_ADMIN;
	GRANT CREATE TRIGGER TO R_ADMIN;
	GRANT CREATE SEQUENCE TO R_ADMIN;
	GRANT CREATE VIEW TO R_ADMIN;
	GRANT SELECT VIEW ON VISTAUSERS TO R_ADMIN;
	GRANT CREATE PROCEDURE TO R_ADMIN;
	GRANT CREATE PUBLIC SYNONYM TO R_ADMIN;
	GRANT CREATE TYPE TO R_ADMIN;
	

	GRANT R_ADMIN TO U_ADMIN;

--	Ingresar a U_ADMIN
	conn U_ADMIN/pass@localhost:1521/dbmultinivel
	
--	Ejecutar scripts
	start rutaScriptCreacion DB
	start rutaScriptLlenado
	start rutaScriptVistas
	
--	Crear sinonimos

	--Tablas
	CREATE PUBLIC SYNONYM CLIENTE FOR U_ADMIN.CLIENTE;
	CREATE PUBLIC SYNONYM CATEGORIA FOR U_ADMIN.CATEGORIA;
	CREATE PUBLIC SYNONYM INVENTARIO FOR U_ADMIN.INVENTARIO;
	CREATE PUBLIC SYNONYM ORDEN FOR U_ADMIN.ORDEN;
	CREATE PUBLIC SYNONYM PAIS FOR U_ADMIN.PAIS;
	CREATE PUBLIC SYNONYM PERIODO FOR U_ADMIN.PERIODO;
	CREATE PUBLIC SYNONYM PRODUCTO FOR U_ADMIN.PRODUCTO;
	CREATE PUBLIC SYNONYM REGION FOR U_ADMIN.REGION;
	CREATE PUBLIC SYNONYM REPRESENTANTE_VENTAS FOR U_ADMIN.REPRESENTANTE_VENTAS;
	
	--Vistas
	CREATE PUBLIC SYNONYM VISTAUSERS FOR U_ADMIN.VISTAUSERS;
	CREATE PUBLIC SYNONYM VISTATOPPRODUCTO FOR U_ADMIN.VISTATOPPRODUCTO;
	CREATE PUBLIC SYNONYM VISTATOPREGION FOR U_ADMIN.VISTATOPREGION;
	CREATE PUBLIC SYNONYM VISTATOPRV FOR U_ADMIN.VISTATOPRV;
	CREATE PUBLIC SYNONYM VISTACALIFICACION FOR U_ADMIN.VISTACALIFICACION;
	CREATE PUBLIC SYNONYM VISTANOMINA FOR U_ADMIN.VISTANOMINA;

--	Crear Rol R_CONNECTION:
	CREATE ROLE R_CONNECTION;
	
	--Permisos
	GRANT CONNECT TO R_CONNECTION;
	GRANT SELECT ON VISTAUSERS TO R_CONNECTION;
	
--	Crear schema U_CONNECTION:
	CREATE USER U_CONNECTION IDENTIFIED BY pass
	DEFAULT TABLESPACE SGADEF
	TEMPORARY TABLESPACE SGATMP
	QUOTA 2M ON SGADEF;

--	Asignar Rol R_CONNECTION:
	GRANT R_CONNECTION TO U_CONNECTION;


	CREATE ROLE R_CLIENTE;
	
	GRANT CONNECT TO R_CLIENTE;
	GRANT INSERT ON ORDEN TO R_CLIENTE;
	GRANT UPDATE(I_ESTADO) ON ORDEN TO R_CLIENTE;
	GRANT UPDATE(Q_CANTIDAD) ON ORDEN TO R_CLIENTE;
	GRANT UPDATE(Q_CALIFICACION) ON ORDEN TO R_CLIENTE;
	GRANT UPDATE(K_TIPO_ID_REP) ON CLIENTE TO R_CLIENTE;
	GRANT UPDATE(K_ID_NUMERO_REP) ON CLIENTE TO R_CLIENTE;
	
	GRANT SELECT ON PAIS TO R_CLIENTE;
	GRANT SELECT ON REGION TO R_CLIENTE;
	GRANT SELECT ON CATEGORIA TO R_CLIENTE;
	GRANT SELECT ON PRODUCTO TO R_CLIENTE;
	GRANT SELECT ON ORDEN TO R_CLIENTE;
	GRANT SELECT ON INVENTARIO TO R_CLIENTE;
	GRANT SELECT ON REPRESENTANTE_VENTAS TO R_CLIENTE;
	GRANT SELECT ON CLIENTE TO R_CLIENTE;
	GRANT SELECT ON PERIODO TO R_CLIENTE;

	
--	Crear schema y asignar rol:
	CREATE USER U_CLIENTE IDENTIFIED BY pass
	DEFAULT TABLESPACE SGADEF
	TEMPORARY TABLESPACE SGATMP
	QUOTA 2M ON SGADEF;

	GRANT R_CLIENTE TO U_CLIENTE;

--	Crear rol R_REPRESENTANTE:
	CREATE ROLE R_REPRESENTANTE;
	
	GRANT CONNECT TO R_REPRESENTANTE;
	GRANT CREATE USER TO R_REPRESENTANTE;
	GRANT GRANT ANY ROLE TO R_REPRESENTANTE;

	GRANT SELECT ON PAIS TO R_REPRESENTANTE;
	GRANT SELECT ON REGION TO R_REPRESENTANTE;
	GRANT SELECT ON CATEGORIA TO R_REPRESENTANTE;
	GRANT SELECT ON PRODUCTO TO R_REPRESENTANTE;
	GRANT SELECT, INSERT ON ORDEN TO R_REPRESENTANTE;
	GRANT UPDATE(Q_CANTIDAD) ON ORDEN TO R_REPRESENTANTE;
	GRANT SELECT ON INVENTARIO TO R_REPRESENTANTE;
	GRANT SELECT ON VISTACALIFICACION TO R_REPRESENTANTE;
	GRANT SELECT, INSERT ON CLIENTE TO R_REPRESENTANTE;
	
--	Crear schema U_REPRESENTANTE:

	CREATE USER U_REPRESENTANTE IDENTIFIED BY pass
	DEFAULT TABLESPACE SGADEF
	TEMPORARY TABLESPACE SGATMP
	QUOTA 2M ON SGADEF;

--	Asignar Rol R_REPRESENTANTE:
	GRANT R_REPRESENTANTE TO U_REPRESENTANTE;

--	Crear rol R_MASTER:
	CREATE ROLE R_MASTER;

	GRANT CONNECT TO R_MASTER;
	GRANT R_REPRESENTANTE TO R_MASTER;
	GRANT SELECT ON VISTANOMINA TO R_MASTER;
	GRANT SELECT ON VISTATOPPRODUCTO TO R_MASTER;
	GRANT SELECT ON VISTATOPREGION TO R_MASTER;
	GRANT SELECT ON VISTATOPRV TO R_MASTER;

	GRANT SELECT, INSERT ON REPRESENTANTE_VENTAS TO R_MASTER;
	
	
--	Crear schema y asignar rol:
	CREATE USER U_MASTER IDENTIFIED BY pass
	DEFAULT TABLESPACE SGADEF
	TEMPORARY TABLESPACE SGATMP
	QUOTA 2M ON SGADEF;

	GRANT R_MASTER TO U_MASTER;
	
--	Crear rol R_CLIENTE
	
	
	COMMIT;
	
	